# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac28d998382f09def25a1a855f7ee8c9d61475f94c0b712dd8e0f3c51b495af4b22d5486f6ad55c6403a32c0a9f7fe75062688ef62d39f515ec8b723eca545df

test:
  secret_key_base: 30df013d9920e7e7d7f9af1f87720f3e35863cd520145117686fb390b175f8d5970fce1ce903b685cd24bc8754dba651d51a35b3114ffdbb751fc23621ea75bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
